version: "3.7"

services:
  postgres-service:
    image: postgres
    container_name: postgres-service
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=my_db
